name = "flickrgroupaddr-flickr-callback-cfworker"
type = "javascript"
zone_id = ""
account_id = ""
route = "https://auth.flickrgroupaddr.com/flickr/oauth/callback*"
workers_dev = false
compatibility_date = "2021-12-06"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
